#%RAML 1.0 Library
types:
  Folder:
    properties:
      name: string
    example:
      name: root folder
  File:
    properties:
      name: string
    example:
      name: file name
# title: NewLibrary
